// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpaomtgbpjxvnamtqhtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwYW9tdGdicGp4dm5hbXRxaHR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNTM1MTYsImV4cCI6MjA2NDgyOTUxNn0.xsTkQb1lXvgifcxLIVGH5ZVLvLuXEvNxyrXf2ynzWF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);